const fs = require('fs');
const path = require('path');

// A quick and dirty way to read the current array since it's hardcoded in TS.
// We can use regex or string manipulation.
const dataPath = path.join(__dirname, '..', 'src', 'lib', 'songs-data.ts');
const dataContent = fs.readFileSync(dataPath, 'utf8');

// The file exports INITIAL_SONGS which is an array of objects.
// Let's extract the array string and parse it.
const startIndex = dataContent.indexOf('[');
const exportFuncIndex = dataContent.indexOf('export function', startIndex);
const endIndex = exportFuncIndex !== -1 
    ? dataContent.lastIndexOf('];', exportFuncIndex) + 1 
    : dataContent.lastIndexOf(']') + 1;
const arrayString = dataContent.substring(startIndex, endIndex);

let INITIAL_SONGS;
try {
    INITIAL_SONGS = eval('(' + arrayString + ')');
} catch (e) {
    console.error("Failed to parse INITIAL_SONGS:", e);
    process.exit(1);
}

// Now we need 10 global songs for each year from 1990 to 2026.
// But wait, are the current songs clearly marked as global vs AR?
// In generate_songs.js, we saw AR songs and global songs were mixed.
// But in songs-data.ts they are just songs. Let's just pick the first 10 for each year, 
// or maybe check the list of global songs from generate_songs.js to identify them?
// The prompt said: "para las 10 mundiales, usa 10 de la actual lista ya creada".
// That just means take 10 songs from the current list for each year.

const globalSongsPerYear = {};
for (let year = 1990; year <= 2026; year++) {
    const songsForYear = INITIAL_SONGS.filter(s => s.year === year);
    if (year === 2026) {
        const global2026 = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'raw_global_songs_2026.json'), 'utf8'));
        globalSongsPerYear[year] = global2026;
    } else {
        if (songsForYear.length < 10) {
            console.warn(`Year ${year} only has ${songsForYear.length} songs in the original list.`);
        }
        // Take exactly 10 songs
        globalSongsPerYear[year] = songsForYear.slice(0, 10).map((s, index) => {
            return {
                ...s,
                id: `global-song-${year}-${index}`
            };
        });
    }
}

// Now we load the AR songs generated by subagents.
// If the files don't exist yet, we just create empty arrays so we can test the script structure.
let finalSongs = [];

for (let year = 1990; year <= 2026; year++) {
    let decadeStart;
    if (year >= 1990 && year <= 1999) decadeStart = 1990;
    else if (year >= 2000 && year <= 2009) decadeStart = 2000;
    else if (year >= 2010 && year <= 2019) decadeStart = 2010;
    else if (year >= 2020 && year <= 2026) decadeStart = 2020;
    
    let decadeEnd = decadeStart === 2020 ? 2026 : decadeStart + 9;
    
    const arFile = path.join(__dirname, '..', `raw_ar_songs_${decadeStart}_${decadeEnd}.json`);
    let arSongs = [];
    if (fs.existsSync(arFile)) {
        const raw = fs.readFileSync(arFile, 'utf8');
        try {
            const allAr = JSON.parse(raw);
            arSongs = allAr.filter(s => s.year === year);
            // Ensure exactly 20 AR songs
            arSongs = arSongs.slice(0, 20).map(s => {
                if (!s.youtube_id) {
                    s.youtube_id = 'NOT_FOUND';
                }
                return s;
            });
        } catch (e) {
            console.error(`Error parsing ${arFile}:`, e);
        }
    }
    
    // Merge
    finalSongs = finalSongs.concat(arSongs, globalSongsPerYear[year]);
}

// Write the intermediate json file for tests
fs.writeFileSync(path.join(__dirname, '..', 'final_songs_data.json'), JSON.stringify(finalSongs, null, 2), 'utf8');

console.log("Built final_songs_data.json");
